// 주요 IATA 공항 데이터 (자동완성용).
// 약 300+개 공항 — 한국·미국 전역·유럽 전역·아시아·중동·아프리카·남미·오세아니아.
// 형식: { code, city, cityEn, country, label, alt }
window.AIRPORTS = [
  // ── 대한민국 ─────────────────────────────────────────
  { code: 'ICN', city: '서울', cityEn: 'Seoul', country: '대한민국', label: '서울 인천 (ICN)', alt: 'incheon seoul', lat: 37.4691, lng: 126.4510 },
  { code: 'GMP', city: '서울', cityEn: 'Seoul', country: '대한민국', label: '서울 김포 (GMP)', alt: 'gimpo seoul', lat: 37.5583, lng: 126.7910 },
  { code: 'PUS', city: '부산', cityEn: 'Busan', country: '대한민국', label: '부산 김해 (PUS)', alt: 'busan gimhae', lat: 35.1795, lng: 128.9380 },
  { code: 'CJU', city: '제주', cityEn: 'Jeju', country: '대한민국', label: '제주 (CJU)', alt: 'jeju', lat: 33.5113, lng: 126.4930 },
  { code: 'TAE', city: '대구', cityEn: 'Daegu', country: '대한민국', label: '대구 (TAE)', alt: 'daegu', lat: 35.8969, lng: 128.6553 },
  { code: 'KWJ', city: '광주', cityEn: 'Gwangju', country: '대한민국', label: '광주 (KWJ)', alt: 'gwangju', lat: 35.1232, lng: 126.8054 },
  { code: 'CJJ', city: '청주', cityEn: 'Cheongju', country: '대한민국', label: '청주 (CJJ)', alt: 'cheongju', lat: 36.7170, lng: 127.4987 },
  { code: 'USN', city: '울산', cityEn: 'Ulsan', country: '대한민국', label: '울산 (USN)', alt: 'ulsan', lat: 35.5935, lng: 129.3520 },
  { code: 'MWX', city: '무안', cityEn: 'Muan', country: '대한민국', label: '무안 (MWX)', alt: 'muan', lat: 34.9914, lng: 126.3828 },
  { code: 'RSU', city: '여수', cityEn: 'Yeosu', country: '대한민국', label: '여수 (RSU)', alt: 'yeosu', lat: 34.8417, lng: 127.6167 },
  { code: 'HIN', city: '사천', cityEn: 'Sacheon', country: '대한민국', label: '사천 (HIN)', alt: 'sacheon jinju', lat: 35.0886, lng: 128.0717 },
  { code: 'KPO', city: '포항', cityEn: 'Pohang', country: '대한민국', label: '포항 (KPO)', alt: 'pohang', lat: 35.9879, lng: 129.4203 },
  { code: 'WJU', city: '원주', cityEn: 'Wonju', country: '대한민국', label: '원주 (WJU)', alt: 'wonju', lat: 37.4381, lng: 127.9603 },
  { code: 'KUV', city: '군산', cityEn: 'Gunsan', country: '대한민국', label: '군산 (KUV)', alt: 'gunsan', lat: 35.9038, lng: 126.6156 },

  // ── 일본 ─────────────────────────────────────────────
  { code: 'NRT', city: '도쿄', cityEn: 'Tokyo', country: '일본', label: '도쿄 나리타 (NRT)', alt: 'tokyo narita', lat: 35.7647, lng: 140.3860 },
  { code: 'HND', city: '도쿄', cityEn: 'Tokyo', country: '일본', label: '도쿄 하네다 (HND)', alt: 'tokyo haneda', lat: 35.5523, lng: 139.7800 },
  { code: 'KIX', city: '오사카', cityEn: 'Osaka', country: '일본', label: '오사카 간사이 (KIX)', alt: 'osaka kansai', lat: 34.4273, lng: 135.2440 },
  { code: 'ITM', city: '오사카', cityEn: 'Osaka', country: '일본', label: '오사카 이타미 (ITM)', alt: 'osaka itami', lat: 34.7855, lng: 135.4380 },
  { code: 'NGO', city: '나고야', cityEn: 'Nagoya', country: '일본', label: '나고야 주부 (NGO)', alt: 'nagoya chubu', lat: 34.8584, lng: 136.8050 },
  { code: 'FUK', city: '후쿠오카', cityEn: 'Fukuoka', country: '일본', label: '후쿠오카 (FUK)', alt: 'fukuoka', lat: 33.5859, lng: 130.4510 },
  { code: 'CTS', city: '삿포로', cityEn: 'Sapporo', country: '일본', label: '삿포로 신치토세 (CTS)', alt: 'sapporo chitose', lat: 42.7752, lng: 141.6920 },
  { code: 'OKA', city: '오키나와', cityEn: 'Okinawa', country: '일본', label: '오키나와 나하 (OKA)', alt: 'okinawa naha', lat: 26.1958, lng: 127.6460 },
  { code: 'HIJ', city: '히로시마', cityEn: 'Hiroshima', country: '일본', label: '히로시마 (HIJ)', alt: 'hiroshima', lat: 34.4361, lng: 132.9190 },
  { code: 'SDJ', city: '센다이', cityEn: 'Sendai', country: '일본', label: '센다이 (SDJ)', alt: 'sendai', lat: 38.1397, lng: 140.9170 },
  { code: 'KOJ', city: '가고시마', cityEn: 'Kagoshima', country: '일본', label: '가고시마 (KOJ)', alt: 'kagoshima', lat: 31.8034, lng: 130.7190 },
  { code: 'KMJ', city: '구마모토', cityEn: 'Kumamoto', country: '일본', label: '구마모토 (KMJ)', alt: 'kumamoto', lat: 32.8373, lng: 130.8550 },
  { code: 'KMI', city: '미야자키', cityEn: 'Miyazaki', country: '일본', label: '미야자키 (KMI)', alt: 'miyazaki', lat: 31.8772, lng: 131.4490 },
  { code: 'TAK', city: '다카마쓰', cityEn: 'Takamatsu', country: '일본', label: '다카마쓰 (TAK)', alt: 'takamatsu', lat: 34.2142, lng: 134.0160 },
  { code: 'KIJ', city: '니가타', cityEn: 'Niigata', country: '일본', label: '니가타 (KIJ)', alt: 'niigata', lat: 37.9559, lng: 139.1210 },
  { code: 'KMQ', city: '고마쓰', cityEn: 'Komatsu', country: '일본', label: '고마쓰 (KMQ)', alt: 'komatsu kanazawa', lat: 36.3946, lng: 136.4070 },

  // ── 중국 ─────────────────────────────────────────────
  { code: 'PEK', city: '베이징', cityEn: 'Beijing', country: '중국', label: '베이징 서우두 (PEK)', alt: 'beijing capital', lat: 40.0801, lng: 116.5850 },
  { code: 'PKX', city: '베이징', cityEn: 'Beijing', country: '중국', label: '베이징 다싱 (PKX)', alt: 'beijing daxing', lat: 39.5098, lng: 116.4106 },
  { code: 'PVG', city: '상하이', cityEn: 'Shanghai', country: '중국', label: '상하이 푸둥 (PVG)', alt: 'shanghai pudong', lat: 31.1434, lng: 121.8050 },
  { code: 'SHA', city: '상하이', cityEn: 'Shanghai', country: '중국', label: '상하이 훙차오 (SHA)', alt: 'shanghai hongqiao', lat: 31.1979, lng: 121.3360 },
  { code: 'CAN', city: '광저우', cityEn: 'Guangzhou', country: '중국', label: '광저우 (CAN)', alt: 'guangzhou', lat: 23.3924, lng: 113.2990 },
  { code: 'SZX', city: '선전', cityEn: 'Shenzhen', country: '중국', label: '선전 (SZX)', alt: 'shenzhen', lat: 22.6393, lng: 113.8110 },
  { code: 'HGH', city: '항저우', cityEn: 'Hangzhou', country: '중국', label: '항저우 (HGH)', alt: 'hangzhou', lat: 30.2295, lng: 120.4340 },
  { code: 'CTU', city: '청두', cityEn: 'Chengdu', country: '중국', label: '청두 (CTU)', alt: 'chengdu', lat: 30.5785, lng: 103.9470 },
  { code: 'TFU', city: '청두', cityEn: 'Chengdu', country: '중국', label: '청두 톈푸 (TFU)', alt: 'chengdu tianfu', lat: 30.3125, lng: 104.4417 },
  { code: 'XIY', city: '시안', cityEn: "Xi'an", country: '중국', label: '시안 (XIY)', alt: 'xian', lat: 34.4471, lng: 108.7520 },
  { code: 'TSN', city: '톈진', cityEn: 'Tianjin', country: '중국', label: '톈진 (TSN)', alt: 'tianjin', lat: 39.1244, lng: 117.3460 },
  { code: 'KMG', city: '쿤밍', cityEn: 'Kunming', country: '중국', label: '쿤밍 (KMG)', alt: 'kunming', lat: 25.1019, lng: 102.9292 },
  { code: 'CKG', city: '충칭', cityEn: 'Chongqing', country: '중국', label: '충칭 (CKG)', alt: 'chongqing', lat: 29.7192, lng: 106.6420 },
  { code: 'WUH', city: '우한', cityEn: 'Wuhan', country: '중국', label: '우한 (WUH)', alt: 'wuhan', lat: 30.7838, lng: 114.2080 },
  { code: 'NKG', city: '난징', cityEn: 'Nanjing', country: '중국', label: '난징 (NKG)', alt: 'nanjing', lat: 31.7420, lng: 118.8620 },
  { code: 'CSX', city: '창사', cityEn: 'Changsha', country: '중국', label: '창사 (CSX)', alt: 'changsha', lat: 28.1892, lng: 113.2200 },
  { code: 'XMN', city: '샤먼', cityEn: 'Xiamen', country: '중국', label: '샤먼 (XMN)', alt: 'xiamen', lat: 24.5440, lng: 118.1280 },
  { code: 'DLC', city: '다롄', cityEn: 'Dalian', country: '중국', label: '다롄 (DLC)', alt: 'dalian', lat: 38.9657, lng: 121.5390 },
  { code: 'SHE', city: '선양', cityEn: 'Shenyang', country: '중국', label: '선양 (SHE)', alt: 'shenyang', lat: 41.6398, lng: 123.4830 },
  { code: 'HRB', city: '하얼빈', cityEn: 'Harbin', country: '중국', label: '하얼빈 (HRB)', alt: 'harbin', lat: 45.6234, lng: 126.2500 },
  { code: 'TAO', city: '칭다오', cityEn: 'Qingdao', country: '중국', label: '칭다오 (TAO)', alt: 'qingdao', lat: 36.2661, lng: 120.3740 },

  // ── 홍콩 / 마카오 / 대만 ────────────────────────────
  { code: 'HKG', city: '홍콩', cityEn: 'Hong Kong', country: '홍콩', label: '홍콩 (HKG)', alt: 'hong kong', lat: 22.3089, lng: 113.9150 },
  { code: 'MFM', city: '마카오', cityEn: 'Macau', country: '마카오', label: '마카오 (MFM)', alt: 'macau', lat: 22.1496, lng: 113.5920 },
  { code: 'TPE', city: '타이페이', cityEn: 'Taipei', country: '대만', label: '타이페이 타오위안 (TPE)', alt: 'taipei taoyuan', lat: 25.0777, lng: 121.2330 },
  { code: 'TSA', city: '타이페이', cityEn: 'Taipei', country: '대만', label: '타이페이 송산 (TSA)', alt: 'taipei songshan', lat: 25.0694, lng: 121.5520 },
  { code: 'KHH', city: '가오슝', cityEn: 'Kaohsiung', country: '대만', label: '가오슝 (KHH)', alt: 'kaohsiung', lat: 22.5771, lng: 120.3500 },
  { code: 'TXG', city: '타이중', cityEn: 'Taichung', country: '대만', label: '타이중 (TXG)', alt: 'taichung', lat: 24.1863, lng: 120.6540 },

  // ── 동남아 ───────────────────────────────────────────
  { code: 'SIN', city: '싱가포르', cityEn: 'Singapore', country: '싱가포르', label: '싱가포르 창이 (SIN)', alt: 'singapore changi', lat: 1.3502, lng: 103.9940 },
  { code: 'BKK', city: '방콕', cityEn: 'Bangkok', country: '태국', label: '방콕 수완나품 (BKK)', alt: 'bangkok suvarnabhumi', lat: 13.6811, lng: 100.7470 },
  { code: 'DMK', city: '방콕', cityEn: 'Bangkok', country: '태국', label: '방콕 돈므앙 (DMK)', alt: 'bangkok don mueang', lat: 13.9126, lng: 100.6070 },
  { code: 'CNX', city: '치앙마이', cityEn: 'Chiang Mai', country: '태국', label: '치앙마이 (CNX)', alt: 'chiang mai', lat: 18.7668, lng: 98.9626 },
  { code: 'HKT', city: '푸켓', cityEn: 'Phuket', country: '태국', label: '푸켓 (HKT)', alt: 'phuket', lat: 8.1132, lng: 98.3169 },
  { code: 'USM', city: '코사무이', cityEn: 'Koh Samui', country: '태국', label: '코사무이 (USM)', alt: 'samui', lat: 9.5478, lng: 100.0620 },
  { code: 'KBV', city: '끄라비', cityEn: 'Krabi', country: '태국', label: '끄라비 (KBV)', alt: 'krabi', lat: 8.0991, lng: 98.9862 },
  { code: 'KUL', city: '쿠알라룸푸르', cityEn: 'Kuala Lumpur', country: '말레이시아', label: '쿠알라룸푸르 (KUL)', alt: 'kuala lumpur', lat: 2.7456, lng: 101.7100 },
  { code: 'PEN', city: '페낭', cityEn: 'Penang', country: '말레이시아', label: '페낭 (PEN)', alt: 'penang', lat: 5.2971, lng: 100.2770 },
  { code: 'LGK', city: '랑카위', cityEn: 'Langkawi', country: '말레이시아', label: '랑카위 (LGK)', alt: 'langkawi', lat: 6.3297, lng: 99.7287 },
  { code: 'BKI', city: '코타키나발루', cityEn: 'Kota Kinabalu', country: '말레이시아', label: '코타키나발루 (BKI)', alt: 'kota kinabalu', lat: 5.9372, lng: 116.0510 },
  { code: 'KCH', city: '쿠칭', cityEn: 'Kuching', country: '말레이시아', label: '쿠칭 (KCH)', alt: 'kuching', lat: 1.4847, lng: 110.3470 },
  { code: 'JHB', city: '조호르바루', cityEn: 'Johor Bahru', country: '말레이시아', label: '조호르바루 (JHB)', alt: 'johor bahru', lat: 1.6413, lng: 103.6700 },
  { code: 'HAN', city: '하노이', cityEn: 'Hanoi', country: '베트남', label: '하노이 (HAN)', alt: 'hanoi', lat: 21.2212, lng: 105.8070 },
  { code: 'SGN', city: '호치민', cityEn: 'Ho Chi Minh City', country: '베트남', label: '호치민 (SGN)', alt: 'ho chi minh saigon', lat: 10.8188, lng: 106.6520 },
  { code: 'DAD', city: '다낭', cityEn: 'Da Nang', country: '베트남', label: '다낭 (DAD)', alt: 'da nang', lat: 16.0439, lng: 108.1990 },
  { code: 'CXR', city: '나트랑', cityEn: 'Nha Trang', country: '베트남', label: '나트랑 (CXR)', alt: 'nha trang cam ranh', lat: 11.9982, lng: 109.2190 },
  { code: 'PQC', city: '푸꾸옥', cityEn: 'Phu Quoc', country: '베트남', label: '푸꾸옥 (PQC)', alt: 'phu quoc', lat: 10.1698, lng: 103.9931 },
  { code: 'VTE', city: '비엔티안', cityEn: 'Vientiane', country: '라오스', label: '비엔티안 (VTE)', alt: 'vientiane', lat: 17.9883, lng: 102.5630 },
  { code: 'LPQ', city: '루앙프라방', cityEn: 'Luang Prabang', country: '라오스', label: '루앙프라방 (LPQ)', alt: 'luang prabang', lat: 19.8973, lng: 102.1610 },
  { code: 'PNH', city: '프놈펜', cityEn: 'Phnom Penh', country: '캄보디아', label: '프놈펜 (PNH)', alt: 'phnom penh', lat: 11.5466, lng: 104.8440 },
  { code: 'REP', city: '시엠립', cityEn: 'Siem Reap', country: '캄보디아', label: '시엠립 (REP)', alt: 'siem reap angkor', lat: 13.4107, lng: 103.8130 },
  { code: 'RGN', city: '양곤', cityEn: 'Yangon', country: '미얀마', label: '양곤 (RGN)', alt: 'yangon', lat: 16.9073, lng: 96.1332 },
  { code: 'MDL', city: '만달레이', cityEn: 'Mandalay', country: '미얀마', label: '만달레이 (MDL)', alt: 'mandalay', lat: 21.7022, lng: 95.9779 },
  { code: 'BWN', city: '반다르스리브가완', cityEn: 'Bandar Seri Begawan', country: '브루나이', label: '반다르스리브가완 (BWN)', alt: 'bandar seri brunei', lat: 4.9442, lng: 114.9280 },
  { code: 'MNL', city: '마닐라', cityEn: 'Manila', country: '필리핀', label: '마닐라 (MNL)', alt: 'manila', lat: 14.5086, lng: 121.0200 },
  { code: 'CEB', city: '세부', cityEn: 'Cebu', country: '필리핀', label: '세부 막탄 (CEB)', alt: 'cebu mactan', lat: 10.3075, lng: 123.9790 },
  { code: 'DVO', city: '다바오', cityEn: 'Davao', country: '필리핀', label: '다바오 (DVO)', alt: 'davao', lat: 7.1255, lng: 125.6460 },
  { code: 'KLO', city: '칼리보', cityEn: 'Kalibo', country: '필리핀', label: '칼리보 (KLO)', alt: 'kalibo boracay', lat: 11.6794, lng: 122.3760 },
  { code: 'MPH', city: '카티클란', cityEn: 'Caticlan', country: '필리핀', label: '카티클란 보라카이 (MPH)', alt: 'caticlan boracay', lat: 11.9245, lng: 121.9540 },
  { code: 'CGK', city: '자카르타', cityEn: 'Jakarta', country: '인도네시아', label: '자카르타 수카르노 (CGK)', alt: 'jakarta soekarno', lat: -6.1256, lng: 106.6560 },
  { code: 'HLP', city: '자카르타', cityEn: 'Jakarta', country: '인도네시아', label: '자카르타 할림 (HLP)', alt: 'jakarta halim', lat: -6.2666, lng: 106.8910 },
  { code: 'DPS', city: '발리', cityEn: 'Bali', country: '인도네시아', label: '발리 덴파사르 (DPS)', alt: 'bali denpasar', lat: -8.7482, lng: 115.1670 },
  { code: 'SUB', city: '수라바야', cityEn: 'Surabaya', country: '인도네시아', label: '수라바야 (SUB)', alt: 'surabaya', lat: -7.3798, lng: 112.7870 },
  { code: 'JOG', city: '족자카르타', cityEn: 'Yogyakarta', country: '인도네시아', label: '족자카르타 (JOG)', alt: 'yogyakarta', lat: -7.7882, lng: 110.4320 },
  { code: 'MES', city: '메단', cityEn: 'Medan', country: '인도네시아', label: '메단 (MES)', alt: 'medan', lat: 3.5592, lng: 98.6711 },
  { code: 'DLI', city: '딜리', cityEn: 'Dili', country: '동티모르', label: '딜리 (DLI)', alt: 'dili timor', lat: 11.7500, lng: 108.3670 },

  // ── 인도 / 남아시아 ─────────────────────────────────
  { code: 'DEL', city: '뉴델리', cityEn: 'New Delhi', country: '인도', label: '뉴델리 (DEL)', alt: 'delhi', lat: 28.5665, lng: 77.1031 },
  { code: 'BOM', city: '뭄바이', cityEn: 'Mumbai', country: '인도', label: '뭄바이 (BOM)', alt: 'mumbai bombay', lat: 19.0887, lng: 72.8679 },
  { code: 'BLR', city: '벵갈루루', cityEn: 'Bengaluru', country: '인도', label: '벵갈루루 (BLR)', alt: 'bangalore bengaluru', lat: 13.1979, lng: 77.7063 },
  { code: 'MAA', city: '첸나이', cityEn: 'Chennai', country: '인도', label: '첸나이 (MAA)', alt: 'chennai madras', lat: 12.9900, lng: 80.1693 },
  { code: 'HYD', city: '하이데라바드', cityEn: 'Hyderabad', country: '인도', label: '하이데라바드 (HYD)', alt: 'hyderabad', lat: 17.2313, lng: 78.4299 },
  { code: 'CCU', city: '콜카타', cityEn: 'Kolkata', country: '인도', label: '콜카타 (CCU)', alt: 'kolkata calcutta', lat: 22.6547, lng: 88.4467 },
  { code: 'COK', city: '코친', cityEn: 'Kochi', country: '인도', label: '코친 (COK)', alt: 'kochi cochin', lat: 10.1520, lng: 76.4019 },
  { code: 'AMD', city: '아마다바드', cityEn: 'Ahmedabad', country: '인도', label: '아마다바드 (AMD)', alt: 'ahmedabad', lat: 23.0772, lng: 72.6347 },
  { code: 'GOI', city: '고아', cityEn: 'Goa', country: '인도', label: '고아 (GOI)', alt: 'goa', lat: 15.3808, lng: 73.8314 },
  { code: 'PNQ', city: '푸네', cityEn: 'Pune', country: '인도', label: '푸네 (PNQ)', alt: 'pune', lat: 18.5821, lng: 73.9197 },
  { code: 'TRV', city: '트리반드룸', cityEn: 'Thiruvananthapuram', country: '인도', label: '트리반드룸 (TRV)', alt: 'trivandrum thiruvananthapuram', lat: 8.4821, lng: 76.9201 },
  { code: 'KTM', city: '카트만두', cityEn: 'Kathmandu', country: '네팔', label: '카트만두 (KTM)', alt: 'kathmandu', lat: 27.6966, lng: 85.3591 },
  { code: 'DAC', city: '다카', cityEn: 'Dhaka', country: '방글라데시', label: '다카 (DAC)', alt: 'dhaka', lat: 23.8433, lng: 90.3978 },
  { code: 'CMB', city: '콜롬보', cityEn: 'Colombo', country: '스리랑카', label: '콜롬보 (CMB)', alt: 'colombo', lat: 7.1808, lng: 79.8841 },
  { code: 'MLE', city: '말레', cityEn: 'Male', country: '몰디브', label: '말레 (MLE)', alt: 'male maldives', lat: 4.1918, lng: 73.5291 },
  { code: 'ISB', city: '이슬라마바드', cityEn: 'Islamabad', country: '파키스탄', label: '이슬라마바드 (ISB)', alt: 'islamabad', lat: 33.5607, lng: 72.8516 },
  { code: 'KHI', city: '카라치', cityEn: 'Karachi', country: '파키스탄', label: '카라치 (KHI)', alt: 'karachi', lat: 24.9065, lng: 67.1608 },
  { code: 'LHE', city: '라호르', cityEn: 'Lahore', country: '파키스탄', label: '라호르 (LHE)', alt: 'lahore', lat: 31.5216, lng: 74.4036 },

  // ── 중앙아시아 / 몽골 ───────────────────────────────
  { code: 'ULN', city: '울란바토르', cityEn: 'Ulaanbaatar', country: '몽골', label: '울란바토르 (ULN)', alt: 'ulaanbaatar', lat: 47.8431, lng: 106.7670 },
  { code: 'ALA', city: '알마티', cityEn: 'Almaty', country: '카자흐스탄', label: '알마티 (ALA)', alt: 'almaty', lat: 43.3521, lng: 77.0405 },
  { code: 'NQZ', city: '아스타나', cityEn: 'Astana', country: '카자흐스탄', label: '아스타나 (NQZ)', alt: 'astana nursultan', lat: 51.0222, lng: 71.4669 },
  { code: 'TAS', city: '타슈켄트', cityEn: 'Tashkent', country: '우즈베키스탄', label: '타슈켄트 (TAS)', alt: 'tashkent', lat: 41.2579, lng: 69.2812 },
  { code: 'FRU', city: '비슈케크', cityEn: 'Bishkek', country: '키르기스스탄', label: '비슈케크 (FRU)', alt: 'bishkek', lat: 43.0613, lng: 74.4776 },

  // ── 미국 (서부) ───────────────────────────────────────
  { code: 'LAX', city: '로스앤젤레스', cityEn: 'Los Angeles', country: '미국', label: '로스앤젤레스 (LAX)', alt: 'los angeles la', lat: 33.9425, lng: -118.4080 },
  { code: 'SFO', city: '샌프란시스코', cityEn: 'San Francisco', country: '미국', label: '샌프란시스코 (SFO)', alt: 'san francisco', lat: 37.6190, lng: -122.3750 },
  { code: 'OAK', city: '오클랜드', cityEn: 'Oakland', country: '미국', label: '오클랜드 (OAK)', alt: 'oakland california', lat: 37.7213, lng: -122.2210 },
  { code: 'SJC', city: '산호세', cityEn: 'San Jose', country: '미국', label: '산호세 (SJC)', alt: 'san jose california', lat: 37.3626, lng: -121.9290 },
  { code: 'SAN', city: '샌디에이고', cityEn: 'San Diego', country: '미국', label: '샌디에이고 (SAN)', alt: 'san diego', lat: 32.7336, lng: -117.1900 },
  { code: 'SMF', city: '새크라멘토', cityEn: 'Sacramento', country: '미국', label: '새크라멘토 (SMF)', alt: 'sacramento', lat: 38.6954, lng: -121.5910 },
  { code: 'SNA', city: '오렌지카운티', cityEn: 'Orange County', country: '미국', label: '오렌지카운티 (SNA)', alt: 'orange county santa ana', lat: 33.6757, lng: -117.8680 },
  { code: 'BUR', city: '버뱅크', cityEn: 'Burbank', country: '미국', label: '버뱅크 (BUR)', alt: 'burbank', lat: 34.2007, lng: -118.3590 },
  { code: 'ONT', city: '온타리오', cityEn: 'Ontario', country: '미국', label: '온타리오 캘리포니아 (ONT)', alt: 'ontario california', lat: 34.0560, lng: -117.6010 },
  { code: 'LGB', city: '롱비치', cityEn: 'Long Beach', country: '미국', label: '롱비치 (LGB)', alt: 'long beach', lat: 33.8177, lng: -118.1520 },
  { code: 'PSP', city: '팜스프링스', cityEn: 'Palm Springs', country: '미국', label: '팜스프링스 (PSP)', alt: 'palm springs', lat: 33.8297, lng: -116.5070 },
  { code: 'FAT', city: '프레즈노', cityEn: 'Fresno', country: '미국', label: '프레즈노 (FAT)', alt: 'fresno', lat: 36.7762, lng: -119.7180 },
  { code: 'SEA', city: '시애틀', cityEn: 'Seattle', country: '미국', label: '시애틀 (SEA)', alt: 'seattle tacoma', lat: 47.4490, lng: -122.3090 },
  { code: 'PDX', city: '포틀랜드', cityEn: 'Portland', country: '미국', label: '포틀랜드 오리건 (PDX)', alt: 'portland oregon', lat: 45.5887, lng: -122.5980 },
  { code: 'GEG', city: '스포캔', cityEn: 'Spokane', country: '미국', label: '스포캔 (GEG)', alt: 'spokane', lat: 47.6199, lng: -117.5340 },
  { code: 'BOI', city: '보이시', cityEn: 'Boise', country: '미국', label: '보이시 (BOI)', alt: 'boise', lat: 43.5644, lng: -116.2230 },
  { code: 'LAS', city: '라스베이거스', cityEn: 'Las Vegas', country: '미국', label: '라스베이거스 (LAS)', alt: 'las vegas', lat: 36.0801, lng: -115.1520 },
  { code: 'RNO', city: '리노', cityEn: 'Reno', country: '미국', label: '리노 (RNO)', alt: 'reno tahoe', lat: 39.4991, lng: -119.7680 },
  { code: 'PHX', city: '피닉스', cityEn: 'Phoenix', country: '미국', label: '피닉스 (PHX)', alt: 'phoenix', lat: 33.4343, lng: -112.0120 },
  { code: 'TUS', city: '투손', cityEn: 'Tucson', country: '미국', label: '투손 (TUS)', alt: 'tucson', lat: 32.1161, lng: -110.9410 },
  { code: 'SLC', city: '솔트레이크시티', cityEn: 'Salt Lake City', country: '미국', label: '솔트레이크시티 (SLC)', alt: 'salt lake city', lat: 40.7884, lng: -111.9780 },
  { code: 'DEN', city: '덴버', cityEn: 'Denver', country: '미국', label: '덴버 (DEN)', alt: 'denver', lat: 39.8617, lng: -104.6730 },
  { code: 'COS', city: '콜로라도스프링스', cityEn: 'Colorado Springs', country: '미국', label: '콜로라도스프링스 (COS)', alt: 'colorado springs', lat: 38.8058, lng: -104.7010 },
  { code: 'ABQ', city: '앨버커키', cityEn: 'Albuquerque', country: '미국', label: '앨버커키 (ABQ)', alt: 'albuquerque', lat: 35.0402, lng: -106.6090 },
  { code: 'ELP', city: '엘파소', cityEn: 'El Paso', country: '미국', label: '엘파소 (ELP)', alt: 'el paso', lat: 31.8072, lng: -106.3780 },
  { code: 'BIL', city: '빌링스', cityEn: 'Billings', country: '미국', label: '빌링스 (BIL)', alt: 'billings montana', lat: 45.8077, lng: -108.5430 },
  { code: 'BZN', city: '보즈먼', cityEn: 'Bozeman', country: '미국', label: '보즈먼 (BZN)', alt: 'bozeman', lat: 45.7775, lng: -111.1530 },
  { code: 'ANC', city: '앵커리지', cityEn: 'Anchorage', country: '미국', label: '앵커리지 (ANC)', alt: 'anchorage alaska', lat: 61.1744, lng: -149.9960 },
  { code: 'FAI', city: '페어뱅크스', cityEn: 'Fairbanks', country: '미국', label: '페어뱅크스 (FAI)', alt: 'fairbanks alaska', lat: 64.8151, lng: -147.8560 },
  { code: 'HNL', city: '호놀룰루', cityEn: 'Honolulu', country: '미국', label: '호놀룰루 (HNL)', alt: 'honolulu hawaii oahu', lat: 21.3206, lng: -157.9242 },
  { code: 'OGG', city: '마우이', cityEn: 'Maui', country: '미국', label: '마우이 카훌루이 (OGG)', alt: 'maui kahului', lat: 20.8986, lng: -156.4300 },
  { code: 'KOA', city: '코나', cityEn: 'Kona', country: '미국', label: '코나 (KOA)', alt: 'kona hawaii', lat: 19.7388, lng: -156.0456 },
  { code: 'LIH', city: '카우아이', cityEn: 'Kauai', country: '미국', label: '카우아이 리후에 (LIH)', alt: 'kauai lihue', lat: 21.9760, lng: -159.3390 },
  { code: 'ITO', city: '힐로', cityEn: 'Hilo', country: '미국', label: '힐로 하와이 (ITO)', alt: 'hilo hawaii', lat: 19.7214, lng: -155.0480 },

  // ── 미국 (중부) ───────────────────────────────────────
  { code: 'ORD', city: '시카고', cityEn: 'Chicago', country: '미국', label: '시카고 오헤어 (ORD)', alt: 'chicago ohare', lat: 41.9786, lng: -87.9048 },
  { code: 'MDW', city: '시카고', cityEn: 'Chicago', country: '미국', label: '시카고 미드웨이 (MDW)', alt: 'chicago midway', lat: 41.7860, lng: -87.7524 },
  { code: 'DFW', city: '댈러스', cityEn: 'Dallas', country: '미국', label: '댈러스 포트워스 (DFW)', alt: 'dallas fort worth', lat: 32.8968, lng: -97.0380 },
  { code: 'DAL', city: '댈러스', cityEn: 'Dallas', country: '미국', label: '댈러스 러브필드 (DAL)', alt: 'dallas love field', lat: 32.8471, lng: -96.8518 },
  { code: 'IAH', city: '휴스턴', cityEn: 'Houston', country: '미국', label: '휴스턴 부시 (IAH)', alt: 'houston bush', lat: 29.9844, lng: -95.3414 },
  { code: 'HOU', city: '휴스턴', cityEn: 'Houston', country: '미국', label: '휴스턴 하비 (HOU)', alt: 'houston hobby', lat: 29.6454, lng: -95.2789 },
  { code: 'AUS', city: '오스틴', cityEn: 'Austin', country: '미국', label: '오스틴 (AUS)', alt: 'austin texas', lat: 30.1945, lng: -97.6699 },
  { code: 'SAT', city: '샌안토니오', cityEn: 'San Antonio', country: '미국', label: '샌안토니오 (SAT)', alt: 'san antonio', lat: 29.5337, lng: -98.4698 },
  { code: 'MSY', city: '뉴올리언스', cityEn: 'New Orleans', country: '미국', label: '뉴올리언스 (MSY)', alt: 'new orleans', lat: 29.9934, lng: -90.2580 },
  { code: 'BNA', city: '내슈빌', cityEn: 'Nashville', country: '미국', label: '내슈빌 (BNA)', alt: 'nashville', lat: 36.1245, lng: -86.6782 },
  { code: 'MEM', city: '멤피스', cityEn: 'Memphis', country: '미국', label: '멤피스 (MEM)', alt: 'memphis', lat: 35.0424, lng: -89.9767 },
  { code: 'STL', city: '세인트루이스', cityEn: 'Saint Louis', country: '미국', label: '세인트루이스 (STL)', alt: 'st louis', lat: 38.7487, lng: -90.3700 },
  { code: 'MCI', city: '캔자스시티', cityEn: 'Kansas City', country: '미국', label: '캔자스시티 (MCI)', alt: 'kansas city', lat: 39.2976, lng: -94.7139 },
  { code: 'OKC', city: '오클라호마시티', cityEn: 'Oklahoma City', country: '미국', label: '오클라호마시티 (OKC)', alt: 'oklahoma city', lat: 35.3931, lng: -97.6007 },
  { code: 'TUL', city: '털사', cityEn: 'Tulsa', country: '미국', label: '털사 (TUL)', alt: 'tulsa', lat: 36.1984, lng: -95.8881 },
  { code: 'LIT', city: '리틀록', cityEn: 'Little Rock', country: '미국', label: '리틀록 (LIT)', alt: 'little rock', lat: 34.7294, lng: -92.2243 },
  { code: 'IND', city: '인디애나폴리스', cityEn: 'Indianapolis', country: '미국', label: '인디애나폴리스 (IND)', alt: 'indianapolis', lat: 39.7173, lng: -86.2944 },
  { code: 'CMH', city: '콜럼버스', cityEn: 'Columbus', country: '미국', label: '콜럼버스 오하이오 (CMH)', alt: 'columbus ohio', lat: 39.9980, lng: -82.8919 },
  { code: 'CLE', city: '클리블랜드', cityEn: 'Cleveland', country: '미국', label: '클리블랜드 (CLE)', alt: 'cleveland', lat: 41.4117, lng: -81.8498 },
  { code: 'CVG', city: '신시내티', cityEn: 'Cincinnati', country: '미국', label: '신시내티 (CVG)', alt: 'cincinnati', lat: 39.0488, lng: -84.6678 },
  { code: 'PIT', city: '피츠버그', cityEn: 'Pittsburgh', country: '미국', label: '피츠버그 (PIT)', alt: 'pittsburgh', lat: 40.4915, lng: -80.2329 },
  { code: 'DTW', city: '디트로이트', cityEn: 'Detroit', country: '미국', label: '디트로이트 (DTW)', alt: 'detroit', lat: 42.2124, lng: -83.3534 },
  { code: 'GRR', city: '그랜드래피즈', cityEn: 'Grand Rapids', country: '미국', label: '그랜드래피즈 (GRR)', alt: 'grand rapids', lat: 42.8808, lng: -85.5228 },
  { code: 'MSP', city: '미니애폴리스', cityEn: 'Minneapolis', country: '미국', label: '미니애폴리스 세인트폴 (MSP)', alt: 'minneapolis st paul', lat: 44.8820, lng: -93.2218 },
  { code: 'MKE', city: '밀워키', cityEn: 'Milwaukee', country: '미국', label: '밀워키 (MKE)', alt: 'milwaukee', lat: 42.9472, lng: -87.8966 },
  { code: 'OMA', city: '오마하', cityEn: 'Omaha', country: '미국', label: '오마하 (OMA)', alt: 'omaha', lat: 41.3032, lng: -95.8941 },
  { code: 'DSM', city: '디모인', cityEn: 'Des Moines', country: '미국', label: '디모인 (DSM)', alt: 'des moines', lat: 41.5340, lng: -93.6631 },
  { code: 'ICT', city: '위치토', cityEn: 'Wichita', country: '미국', label: '위치토 (ICT)', alt: 'wichita', lat: 37.6499, lng: -97.4331 },
  { code: 'LBB', city: '러벅', cityEn: 'Lubbock', country: '미국', label: '러벅 (LBB)', alt: 'lubbock', lat: 33.6636, lng: -101.8230 },

  // ── 미국 (동부 / 남동부) ──────────────────────────────
  { code: 'JFK', city: '뉴욕', cityEn: 'New York', country: '미국', label: '뉴욕 JFK (JFK)', alt: 'new york jfk kennedy', lat: 40.6398, lng: -73.7789 },
  { code: 'LGA', city: '뉴욕', cityEn: 'New York', country: '미국', label: '뉴욕 라가디아 (LGA)', alt: 'new york laguardia', lat: 40.7772, lng: -73.8726 },
  { code: 'EWR', city: '뉴욕', cityEn: 'New York', country: '미국', label: '뉴욕 뉴어크 (EWR)', alt: 'new york newark', lat: 40.6925, lng: -74.1687 },
  { code: 'BOS', city: '보스턴', cityEn: 'Boston', country: '미국', label: '보스턴 (BOS)', alt: 'boston', lat: 42.3643, lng: -71.0052 },
  { code: 'PVD', city: '프로비던스', cityEn: 'Providence', country: '미국', label: '프로비던스 (PVD)', alt: 'providence rhode island', lat: 41.7326, lng: -71.4204 },
  { code: 'BDL', city: '하트퍼드', cityEn: 'Hartford', country: '미국', label: '하트퍼드 (BDL)', alt: 'hartford bradley connecticut', lat: 41.9389, lng: -72.6832 },
  { code: 'MHT', city: '맨체스터', cityEn: 'Manchester', country: '미국', label: '맨체스터 NH (MHT)', alt: 'manchester new hampshire', lat: 42.9326, lng: -71.4357 },
  { code: 'BTV', city: '벌링턴', cityEn: 'Burlington', country: '미국', label: '벌링턴 버몬트 (BTV)', alt: 'burlington vermont', lat: 44.4719, lng: -73.1533 },
  { code: 'PWM', city: '포틀랜드', cityEn: 'Portland Maine', country: '미국', label: '포틀랜드 메인 (PWM)', alt: 'portland maine', lat: 43.6462, lng: -70.3093 },
  { code: 'BGR', city: '뱅고', cityEn: 'Bangor', country: '미국', label: '뱅고 (BGR)', alt: 'bangor maine', lat: 44.8074, lng: -68.8281 },
  { code: 'PHL', city: '필라델피아', cityEn: 'Philadelphia', country: '미국', label: '필라델피아 (PHL)', alt: 'philadelphia', lat: 39.8719, lng: -75.2411 },
  { code: 'BWI', city: '볼티모어', cityEn: 'Baltimore', country: '미국', label: '볼티모어 워싱턴 (BWI)', alt: 'baltimore washington', lat: 39.1754, lng: -76.6683 },
  { code: 'IAD', city: '워싱턴', cityEn: 'Washington', country: '미국', label: '워싱턴 덜레스 (IAD)', alt: 'washington dulles dc', lat: 38.9445, lng: -77.4558 },
  { code: 'DCA', city: '워싱턴', cityEn: 'Washington', country: '미국', label: '워싱턴 레이건 (DCA)', alt: 'washington reagan dc', lat: 38.8521, lng: -77.0377 },
  { code: 'RIC', city: '리치먼드', cityEn: 'Richmond', country: '미국', label: '리치먼드 (RIC)', alt: 'richmond virginia', lat: 37.5052, lng: -77.3197 },
  { code: 'ORF', city: '노포크', cityEn: 'Norfolk', country: '미국', label: '노포크 (ORF)', alt: 'norfolk virginia', lat: 36.8946, lng: -76.2012 },
  { code: 'CLT', city: '샬럿', cityEn: 'Charlotte', country: '미국', label: '샬럿 (CLT)', alt: 'charlotte', lat: 35.2140, lng: -80.9431 },
  { code: 'RDU', city: '롤리', cityEn: 'Raleigh', country: '미국', label: '롤리 더럼 (RDU)', alt: 'raleigh durham', lat: 35.8776, lng: -78.7875 },
  { code: 'GSO', city: '그린즈버러', cityEn: 'Greensboro', country: '미국', label: '그린즈버러 (GSO)', alt: 'greensboro', lat: 36.0978, lng: -79.9373 },
  { code: 'AVL', city: '애슈빌', cityEn: 'Asheville', country: '미국', label: '애슈빌 (AVL)', alt: 'asheville', lat: 35.4362, lng: -82.5418 },
  { code: 'CHS', city: '찰스턴', cityEn: 'Charleston', country: '미국', label: '찰스턴 SC (CHS)', alt: 'charleston south carolina', lat: 32.8986, lng: -80.0405 },
  { code: 'GSP', city: '그린빌', cityEn: 'Greenville', country: '미국', label: '그린빌-스파탄버그 (GSP)', alt: 'greenville spartanburg', lat: 34.8957, lng: -82.2189 },
  { code: 'SAV', city: '사바나', cityEn: 'Savannah', country: '미국', label: '사바나 (SAV)', alt: 'savannah', lat: 32.1276, lng: -81.2021 },
  { code: 'ATL', city: '애틀랜타', cityEn: 'Atlanta', country: '미국', label: '애틀랜타 (ATL)', alt: 'atlanta', lat: 33.6367, lng: -84.4281 },
  { code: 'JAX', city: '잭슨빌', cityEn: 'Jacksonville', country: '미국', label: '잭슨빌 (JAX)', alt: 'jacksonville', lat: 30.4941, lng: -81.6879 },
  { code: 'MCO', city: '올랜도', cityEn: 'Orlando', country: '미국', label: '올랜도 (MCO)', alt: 'orlando', lat: 28.4294, lng: -81.3090 },
  { code: 'TPA', city: '탬파', cityEn: 'Tampa', country: '미국', label: '탬파 (TPA)', alt: 'tampa', lat: 27.9755, lng: -82.5332 },
  { code: 'MIA', city: '마이애미', cityEn: 'Miami', country: '미국', label: '마이애미 (MIA)', alt: 'miami', lat: 25.7932, lng: -80.2906 },
  { code: 'FLL', city: '포트로더데일', cityEn: 'Fort Lauderdale', country: '미국', label: '포트로더데일 (FLL)', alt: 'fort lauderdale', lat: 26.0726, lng: -80.1527 },
  { code: 'PBI', city: '팜비치', cityEn: 'West Palm Beach', country: '미국', label: '웨스트팜비치 (PBI)', alt: 'palm beach', lat: 26.6832, lng: -80.0956 },
  { code: 'RSW', city: '포트마이어스', cityEn: 'Fort Myers', country: '미국', label: '포트마이어스 (RSW)', alt: 'fort myers southwest florida', lat: 26.5362, lng: -81.7552 },
  { code: 'BHM', city: '버밍엄', cityEn: 'Birmingham', country: '미국', label: '버밍엄 AL (BHM)', alt: 'birmingham alabama', lat: 33.5629, lng: -86.7535 },
  { code: 'HSV', city: '헌츠빌', cityEn: 'Huntsville', country: '미국', label: '헌츠빌 (HSV)', alt: 'huntsville', lat: 34.6372, lng: -86.7751 },
  { code: 'BUF', city: '버팔로', cityEn: 'Buffalo', country: '미국', label: '버팔로 (BUF)', alt: 'buffalo', lat: 42.9405, lng: -78.7322 },
  { code: 'ROC', city: '로체스터', cityEn: 'Rochester', country: '미국', label: '로체스터 (ROC)', alt: 'rochester new york', lat: 43.1189, lng: -77.6724 },
  { code: 'ALB', city: '올버니', cityEn: 'Albany', country: '미국', label: '올버니 (ALB)', alt: 'albany new york', lat: 42.7483, lng: -73.8017 },
  { code: 'TYS', city: '녹스빌', cityEn: 'Knoxville', country: '미국', label: '녹스빌 (TYS)', alt: 'knoxville', lat: 35.8110, lng: -83.9940 },
  { code: 'SDF', city: '루이빌', cityEn: 'Louisville', country: '미국', label: '루이빌 (SDF)', alt: 'louisville', lat: 38.1744, lng: -85.7360 },

  // ── 캐나다 ───────────────────────────────────────────
  { code: 'YVR', city: '밴쿠버', cityEn: 'Vancouver', country: '캐나다', label: '밴쿠버 (YVR)', alt: 'vancouver', lat: 49.1939, lng: -123.1840 },
  { code: 'YYZ', city: '토론토', cityEn: 'Toronto', country: '캐나다', label: '토론토 피어슨 (YYZ)', alt: 'toronto pearson', lat: 43.6772, lng: -79.6306 },
  { code: 'YTZ', city: '토론토', cityEn: 'Toronto', country: '캐나다', label: '토론토 시티 빌리비숍 (YTZ)', alt: 'toronto billy bishop city', lat: 43.6275, lng: -79.3962 },
  { code: 'YUL', city: '몬트리올', cityEn: 'Montreal', country: '캐나다', label: '몬트리올 (YUL)', alt: 'montreal', lat: 45.4706, lng: -73.7408 },
  { code: 'YOW', city: '오타와', cityEn: 'Ottawa', country: '캐나다', label: '오타와 (YOW)', alt: 'ottawa', lat: 45.3225, lng: -75.6692 },
  { code: 'YYC', city: '캘거리', cityEn: 'Calgary', country: '캐나다', label: '캘거리 (YYC)', alt: 'calgary', lat: 51.1139, lng: -114.0200 },
  { code: 'YEG', city: '에드먼턴', cityEn: 'Edmonton', country: '캐나다', label: '에드먼턴 (YEG)', alt: 'edmonton', lat: 53.3097, lng: -113.5800 },
  { code: 'YHZ', city: '핼리팩스', cityEn: 'Halifax', country: '캐나다', label: '핼리팩스 (YHZ)', alt: 'halifax', lat: 44.8808, lng: -63.5086 },
  { code: 'YQB', city: '퀘벡시티', cityEn: 'Quebec City', country: '캐나다', label: '퀘벡시티 (YQB)', alt: 'quebec city', lat: 46.7911, lng: -71.3933 },
  { code: 'YWG', city: '위니펙', cityEn: 'Winnipeg', country: '캐나다', label: '위니펙 (YWG)', alt: 'winnipeg', lat: 49.9100, lng: -97.2399 },

  // ── 멕시코 ───────────────────────────────────────────
  { code: 'MEX', city: '멕시코시티', cityEn: 'Mexico City', country: '멕시코', label: '멕시코시티 (MEX)', alt: 'mexico city', lat: 19.4363, lng: -99.0721 },
  { code: 'CUN', city: '칸쿤', cityEn: 'Cancun', country: '멕시코', label: '칸쿤 (CUN)', alt: 'cancun', lat: 21.0365, lng: -86.8771 },
  { code: 'GDL', city: '과달라하라', cityEn: 'Guadalajara', country: '멕시코', label: '과달라하라 (GDL)', alt: 'guadalajara', lat: 20.5218, lng: -103.3110 },
  { code: 'MTY', city: '몬테레이', cityEn: 'Monterrey', country: '멕시코', label: '몬테레이 (MTY)', alt: 'monterrey', lat: 25.7785, lng: -100.1070 },
  { code: 'SJD', city: '로스카보스', cityEn: 'Los Cabos', country: '멕시코', label: '로스카보스 (SJD)', alt: 'los cabos cabo san lucas', lat: 23.1518, lng: -109.7210 },
  { code: 'PVR', city: '푸에르토바야르타', cityEn: 'Puerto Vallarta', country: '멕시코', label: '푸에르토바야르타 (PVR)', alt: 'puerto vallarta', lat: 20.6801, lng: -105.2540 },
  { code: 'TIJ', city: '티후아나', cityEn: 'Tijuana', country: '멕시코', label: '티후아나 (TIJ)', alt: 'tijuana', lat: 32.5411, lng: -116.9700 },

  // ── 유럽 (영국 / 아일랜드) ──────────────────────────
  { code: 'LHR', city: '런던', cityEn: 'London', country: '영국', label: '런던 히드로 (LHR)', alt: 'london heathrow', lat: 51.4706, lng: -0.4619 },
  { code: 'LGW', city: '런던', cityEn: 'London', country: '영국', label: '런던 개트윅 (LGW)', alt: 'london gatwick', lat: 51.1481, lng: -0.1903 },
  { code: 'STN', city: '런던', cityEn: 'London', country: '영국', label: '런던 스탠스테드 (STN)', alt: 'london stansted', lat: 51.8850, lng: 0.2350 },
  { code: 'LTN', city: '런던', cityEn: 'London', country: '영국', label: '런던 루턴 (LTN)', alt: 'london luton', lat: 51.8747, lng: -0.3683 },
  { code: 'LCY', city: '런던', cityEn: 'London', country: '영국', label: '런던 시티 (LCY)', alt: 'london city', lat: 51.5053, lng: 0.0553 },
  { code: 'MAN', city: '맨체스터', cityEn: 'Manchester', country: '영국', label: '맨체스터 (MAN)', alt: 'manchester uk', lat: 53.3537, lng: -2.2750 },
  { code: 'EDI', city: '에든버러', cityEn: 'Edinburgh', country: '영국', label: '에든버러 (EDI)', alt: 'edinburgh', lat: 55.9500, lng: -3.3725 },
  { code: 'GLA', city: '글래스고', cityEn: 'Glasgow', country: '영국', label: '글래스고 (GLA)', alt: 'glasgow', lat: 55.8719, lng: -4.4331 },
  { code: 'BHX', city: '버밍엄', cityEn: 'Birmingham', country: '영국', label: '버밍엄 영국 (BHX)', alt: 'birmingham uk', lat: 52.4539, lng: -1.7480 },
  { code: 'BRS', city: '브리스톨', cityEn: 'Bristol', country: '영국', label: '브리스톨 (BRS)', alt: 'bristol', lat: 51.3827, lng: -2.7191 },
  { code: 'NCL', city: '뉴캐슬', cityEn: 'Newcastle', country: '영국', label: '뉴캐슬 (NCL)', alt: 'newcastle', lat: 55.0375, lng: -1.6917 },
  { code: 'LBA', city: '리즈', cityEn: 'Leeds', country: '영국', label: '리즈 브래드퍼드 (LBA)', alt: 'leeds bradford', lat: 53.8659, lng: -1.6606 },
  { code: 'ABZ', city: '애버딘', cityEn: 'Aberdeen', country: '영국', label: '애버딘 (ABZ)', alt: 'aberdeen', lat: 57.2019, lng: -2.1978 },
  { code: 'BFS', city: '벨파스트', cityEn: 'Belfast', country: '영국', label: '벨파스트 (BFS)', alt: 'belfast', lat: 54.6575, lng: -6.2158 },
  { code: 'DUB', city: '더블린', cityEn: 'Dublin', country: '아일랜드', label: '더블린 (DUB)', alt: 'dublin', lat: 53.4213, lng: -6.2701 },
  { code: 'ORK', city: '코크', cityEn: 'Cork', country: '아일랜드', label: '코크 (ORK)', alt: 'cork ireland', lat: 51.8413, lng: -8.4911 },
  { code: 'SNN', city: '섀넌', cityEn: 'Shannon', country: '아일랜드', label: '섀넌 (SNN)', alt: 'shannon', lat: 52.7020, lng: -8.9248 },

  // ── 유럽 (프랑스 / 베네룩스) ────────────────────────
  { code: 'CDG', city: '파리', cityEn: 'Paris', country: '프랑스', label: '파리 샤를드골 (CDG)', alt: 'paris charles de gaulle', lat: 49.0128, lng: 2.5500 },
  { code: 'ORY', city: '파리', cityEn: 'Paris', country: '프랑스', label: '파리 오를리 (ORY)', alt: 'paris orly', lat: 48.7233, lng: 2.3794 },
  { code: 'BVA', city: '파리', cityEn: 'Paris', country: '프랑스', label: '파리 보베 (BVA)', alt: 'paris beauvais', lat: 49.4544, lng: 2.1128 },
  { code: 'NCE', city: '니스', cityEn: 'Nice', country: '프랑스', label: '니스 (NCE)', alt: 'nice cote azur', lat: 43.6584, lng: 7.2159 },
  { code: 'LYS', city: '리옹', cityEn: 'Lyon', country: '프랑스', label: '리옹 (LYS)', alt: 'lyon', lat: 45.7256, lng: 5.0811 },
  { code: 'MRS', city: '마르세유', cityEn: 'Marseille', country: '프랑스', label: '마르세유 (MRS)', alt: 'marseille', lat: 43.4393, lng: 5.2214 },
  { code: 'TLS', city: '툴루즈', cityEn: 'Toulouse', country: '프랑스', label: '툴루즈 (TLS)', alt: 'toulouse', lat: 43.6291, lng: 1.3638 },
  { code: 'BOD', city: '보르도', cityEn: 'Bordeaux', country: '프랑스', label: '보르도 (BOD)', alt: 'bordeaux', lat: 44.8283, lng: -0.7156 },
  { code: 'NTE', city: '낭트', cityEn: 'Nantes', country: '프랑스', label: '낭트 (NTE)', alt: 'nantes', lat: 47.1532, lng: -1.6107 },
  { code: 'BES', city: '브레스트', cityEn: 'Brest', country: '프랑스', label: '브레스트 (BES)', alt: 'brest', lat: 48.4479, lng: -4.4185 },
  { code: 'BSL', city: '바젤', cityEn: 'Basel', country: '스위스', label: '바젤 뮐루즈 (BSL)', alt: 'basel mulhouse', lat: 47.5900, lng: 7.5292 },
  { code: 'AMS', city: '암스테르담', cityEn: 'Amsterdam', country: '네덜란드', label: '암스테르담 (AMS)', alt: 'amsterdam schiphol', lat: 52.3086, lng: 4.7639 },
  { code: 'EIN', city: '에인트호번', cityEn: 'Eindhoven', country: '네덜란드', label: '에인트호번 (EIN)', alt: 'eindhoven', lat: 51.4501, lng: 5.3745 },
  { code: 'RTM', city: '로테르담', cityEn: 'Rotterdam', country: '네덜란드', label: '로테르담 (RTM)', alt: 'rotterdam', lat: 51.9569, lng: 4.4372 },
  { code: 'BRU', city: '브뤼셀', cityEn: 'Brussels', country: '벨기에', label: '브뤼셀 (BRU)', alt: 'brussels', lat: 50.9014, lng: 4.4844 },
  { code: 'CRL', city: '브뤼셀', cityEn: 'Brussels', country: '벨기에', label: '브뤼셀 샤를루아 (CRL)', alt: 'brussels charleroi', lat: 50.4592, lng: 4.4538 },
  { code: 'ANR', city: '안트베르펜', cityEn: 'Antwerp', country: '벨기에', label: '안트베르펜 (ANR)', alt: 'antwerp', lat: 51.1894, lng: 4.4603 },
  { code: 'LUX', city: '룩셈부르크', cityEn: 'Luxembourg', country: '룩셈부르크', label: '룩셈부르크 (LUX)', alt: 'luxembourg', lat: 49.6233, lng: 6.2044 },

  // ── 유럽 (독일·오스트리아·스위스) ──────────────────
  { code: 'FRA', city: '프랑크푸르트', cityEn: 'Frankfurt', country: '독일', label: '프랑크푸르트 (FRA)', alt: 'frankfurt', lat: 50.0333, lng: 8.5706 },
  { code: 'MUC', city: '뮌헨', cityEn: 'Munich', country: '독일', label: '뮌헨 (MUC)', alt: 'munich', lat: 48.3538, lng: 11.7861 },
  { code: 'BER', city: '베를린', cityEn: 'Berlin', country: '독일', label: '베를린 (BER)', alt: 'berlin brandenburg', lat: 52.3667, lng: 13.5033 },
  { code: 'HAM', city: '함부르크', cityEn: 'Hamburg', country: '독일', label: '함부르크 (HAM)', alt: 'hamburg', lat: 53.6304, lng: 9.9882 },
  { code: 'DUS', city: '뒤셀도르프', cityEn: 'Dusseldorf', country: '독일', label: '뒤셀도르프 (DUS)', alt: 'dusseldorf duesseldorf', lat: 51.2895, lng: 6.7668 },
  { code: 'CGN', city: '쾰른', cityEn: 'Cologne', country: '독일', label: '쾰른 본 (CGN)', alt: 'cologne koeln bonn', lat: 50.8659, lng: 7.1427 },
  { code: 'STR', city: '슈투트가르트', cityEn: 'Stuttgart', country: '독일', label: '슈투트가르트 (STR)', alt: 'stuttgart', lat: 48.6899, lng: 9.2220 },
  { code: 'HAJ', city: '하노버', cityEn: 'Hannover', country: '독일', label: '하노버 (HAJ)', alt: 'hannover hanover', lat: 52.4611, lng: 9.6851 },
  { code: 'NUE', city: '뉘른베르크', cityEn: 'Nuremberg', country: '독일', label: '뉘른베르크 (NUE)', alt: 'nuremberg nurnberg', lat: 49.4987, lng: 11.0781 },
  { code: 'LEJ', city: '라이프치히', cityEn: 'Leipzig', country: '독일', label: '라이프치히 할레 (LEJ)', alt: 'leipzig halle', lat: 51.4239, lng: 12.2364 },
  { code: 'DRS', city: '드레스덴', cityEn: 'Dresden', country: '독일', label: '드레스덴 (DRS)', alt: 'dresden', lat: 51.1328, lng: 13.7672 },
  { code: 'BRE', city: '브레멘', cityEn: 'Bremen', country: '독일', label: '브레멘 (BRE)', alt: 'bremen', lat: 53.0475, lng: 8.7867 },
  { code: 'VIE', city: '빈', cityEn: 'Vienna', country: '오스트리아', label: '빈 (VIE)', alt: 'vienna wien', lat: 48.1103, lng: 16.5697 },
  { code: 'SZG', city: '잘츠부르크', cityEn: 'Salzburg', country: '오스트리아', label: '잘츠부르크 (SZG)', alt: 'salzburg', lat: 47.7933, lng: 13.0043 },
  { code: 'INN', city: '인스브루크', cityEn: 'Innsbruck', country: '오스트리아', label: '인스브루크 (INN)', alt: 'innsbruck', lat: 47.2602, lng: 11.3440 },
  { code: 'GRZ', city: '그라츠', cityEn: 'Graz', country: '오스트리아', label: '그라츠 (GRZ)', alt: 'graz', lat: 46.9911, lng: 15.4396 },
  { code: 'ZRH', city: '취리히', cityEn: 'Zurich', country: '스위스', label: '취리히 (ZRH)', alt: 'zurich', lat: 47.4647, lng: 8.5492 },
  { code: 'GVA', city: '제네바', cityEn: 'Geneva', country: '스위스', label: '제네바 (GVA)', alt: 'geneva', lat: 46.2381, lng: 6.1090 },
  { code: 'BRN', city: '베른', cityEn: 'Bern', country: '스위스', label: '베른 (BRN)', alt: 'bern', lat: 46.9141, lng: 7.4971 },

  // ── 유럽 (이탈리아·스페인·포르투갈) ─────────────────
  { code: 'FCO', city: '로마', cityEn: 'Rome', country: '이탈리아', label: '로마 피우미치노 (FCO)', alt: 'rome fiumicino', lat: 41.8003, lng: 12.2389 },
  { code: 'CIA', city: '로마', cityEn: 'Rome', country: '이탈리아', label: '로마 챔피노 (CIA)', alt: 'rome ciampino', lat: 41.7994, lng: 12.5949 },
  { code: 'MXP', city: '밀라노', cityEn: 'Milan', country: '이탈리아', label: '밀라노 말펜사 (MXP)', alt: 'milan malpensa', lat: 45.6306, lng: 8.7281 },
  { code: 'LIN', city: '밀라노', cityEn: 'Milan', country: '이탈리아', label: '밀라노 리나테 (LIN)', alt: 'milan linate', lat: 45.4451, lng: 9.2767 },
  { code: 'BGY', city: '밀라노', cityEn: 'Milan', country: '이탈리아', label: '밀라노 베르가모 (BGY)', alt: 'milan bergamo', lat: 45.6739, lng: 9.7042 },
  { code: 'VCE', city: '베네치아', cityEn: 'Venice', country: '이탈리아', label: '베네치아 (VCE)', alt: 'venice marco polo', lat: 45.5053, lng: 12.3519 },
  { code: 'NAP', city: '나폴리', cityEn: 'Naples', country: '이탈리아', label: '나폴리 (NAP)', alt: 'naples napoli', lat: 40.8860, lng: 14.2908 },
  { code: 'BLQ', city: '볼로냐', cityEn: 'Bologna', country: '이탈리아', label: '볼로냐 (BLQ)', alt: 'bologna', lat: 44.5354, lng: 11.2887 },
  { code: 'PSA', city: '피사', cityEn: 'Pisa', country: '이탈리아', label: '피사 (PSA)', alt: 'pisa', lat: 43.6839, lng: 10.3927 },
  { code: 'FLR', city: '피렌체', cityEn: 'Florence', country: '이탈리아', label: '피렌체 (FLR)', alt: 'florence firenze', lat: 43.8100, lng: 11.2051 },
  { code: 'TRN', city: '토리노', cityEn: 'Turin', country: '이탈리아', label: '토리노 (TRN)', alt: 'turin torino', lat: 45.2008, lng: 7.6496 },
  { code: 'VRN', city: '베로나', cityEn: 'Verona', country: '이탈리아', label: '베로나 (VRN)', alt: 'verona', lat: 45.3957, lng: 10.8885 },
  { code: 'CTA', city: '카타니아', cityEn: 'Catania', country: '이탈리아', label: '카타니아 시칠리아 (CTA)', alt: 'catania sicily', lat: 37.4668, lng: 15.0664 },
  { code: 'PMO', city: '팔레르모', cityEn: 'Palermo', country: '이탈리아', label: '팔레르모 (PMO)', alt: 'palermo', lat: 38.1760, lng: 13.0910 },
  { code: 'BRI', city: '바리', cityEn: 'Bari', country: '이탈리아', label: '바리 (BRI)', alt: 'bari', lat: 41.1389, lng: 16.7606 },
  { code: 'CAG', city: '칼리아리', cityEn: 'Cagliari', country: '이탈리아', label: '칼리아리 (CAG)', alt: 'cagliari sardinia', lat: 39.2515, lng: 9.0543 },
  { code: 'MAD', city: '마드리드', cityEn: 'Madrid', country: '스페인', label: '마드리드 (MAD)', alt: 'madrid barajas', lat: 40.4719, lng: -3.5626 },
  { code: 'BCN', city: '바르셀로나', cityEn: 'Barcelona', country: '스페인', label: '바르셀로나 (BCN)', alt: 'barcelona', lat: 41.2971, lng: 2.0785 },
  { code: 'AGP', city: '말라가', cityEn: 'Malaga', country: '스페인', label: '말라가 (AGP)', alt: 'malaga', lat: 36.6749, lng: -4.4991 },
  { code: 'VLC', city: '발렌시아', cityEn: 'Valencia', country: '스페인', label: '발렌시아 (VLC)', alt: 'valencia', lat: 39.4893, lng: -0.4816 },
  { code: 'BIO', city: '빌바오', cityEn: 'Bilbao', country: '스페인', label: '빌바오 (BIO)', alt: 'bilbao', lat: 43.3011, lng: -2.9106 },
  { code: 'SVQ', city: '세비야', cityEn: 'Seville', country: '스페인', label: '세비야 (SVQ)', alt: 'seville sevilla', lat: 37.4180, lng: -5.8931 },
  { code: 'ALC', city: '알리칸테', cityEn: 'Alicante', country: '스페인', label: '알리칸테 (ALC)', alt: 'alicante', lat: 38.2822, lng: -0.5582 },
  { code: 'PMI', city: '팔마', cityEn: 'Palma', country: '스페인', label: '팔마 데 마요르카 (PMI)', alt: 'palma mallorca majorca', lat: 39.5517, lng: 2.7388 },
  { code: 'IBZ', city: '이비자', cityEn: 'Ibiza', country: '스페인', label: '이비자 (IBZ)', alt: 'ibiza', lat: 38.8729, lng: 1.3731 },
  { code: 'TFS', city: '테네리페', cityEn: 'Tenerife', country: '스페인', label: '테네리페 남부 (TFS)', alt: 'tenerife south', lat: 28.0445, lng: -16.5725 },
  { code: 'TFN', city: '테네리페', cityEn: 'Tenerife', country: '스페인', label: '테네리페 북부 (TFN)', alt: 'tenerife north', lat: 28.4827, lng: -16.3415 },
  { code: 'LPA', city: '라스팔마스', cityEn: 'Las Palmas', country: '스페인', label: '라스팔마스 그란카나리아 (LPA)', alt: 'las palmas gran canaria', lat: 27.9319, lng: -15.3866 },
  { code: 'LIS', city: '리스본', cityEn: 'Lisbon', country: '포르투갈', label: '리스본 (LIS)', alt: 'lisbon lisboa', lat: 38.7813, lng: -9.1359 },
  { code: 'OPO', city: '포르투', cityEn: 'Porto', country: '포르투갈', label: '포르투 (OPO)', alt: 'porto', lat: 41.2481, lng: -8.6814 },
  { code: 'FAO', city: '파루', cityEn: 'Faro', country: '포르투갈', label: '파루 (FAO)', alt: 'faro algarve', lat: 37.0144, lng: -7.9659 },
  { code: 'FNC', city: '푼샬', cityEn: 'Funchal', country: '포르투갈', label: '푼샬 마데이라 (FNC)', alt: 'funchal madeira', lat: 32.6979, lng: -16.7745 },

  // ── 유럽 (북유럽) ───────────────────────────────────
  { code: 'CPH', city: '코펜하겐', cityEn: 'Copenhagen', country: '덴마크', label: '코펜하겐 (CPH)', alt: 'copenhagen kobenhavn', lat: 55.6179, lng: 12.6560 },
  { code: 'BLL', city: '빌룬', cityEn: 'Billund', country: '덴마크', label: '빌룬 (BLL)', alt: 'billund', lat: 55.7403, lng: 9.1518 },
  { code: 'AAR', city: '오르후스', cityEn: 'Aarhus', country: '덴마크', label: '오르후스 (AAR)', alt: 'aarhus', lat: 56.3000, lng: 10.6190 },
  { code: 'ARN', city: '스톡홀름', cityEn: 'Stockholm', country: '스웨덴', label: '스톡홀름 알란다 (ARN)', alt: 'stockholm arlanda', lat: 59.6519, lng: 17.9186 },
  { code: 'BMA', city: '스톡홀름', cityEn: 'Stockholm', country: '스웨덴', label: '스톡홀름 브로마 (BMA)', alt: 'stockholm bromma', lat: 59.3544, lng: 17.9417 },
  { code: 'GOT', city: '예테보리', cityEn: 'Gothenburg', country: '스웨덴', label: '예테보리 (GOT)', alt: 'gothenburg goteborg', lat: 57.6628, lng: 12.2798 },
  { code: 'MMX', city: '말뫼', cityEn: 'Malmo', country: '스웨덴', label: '말뫼 (MMX)', alt: 'malmo', lat: 55.5363, lng: 13.3762 },
  { code: 'OSL', city: '오슬로', cityEn: 'Oslo', country: '노르웨이', label: '오슬로 가르데르모엔 (OSL)', alt: 'oslo gardermoen', lat: 60.1210, lng: 11.0502 },
  { code: 'BGO', city: '베르겐', cityEn: 'Bergen', country: '노르웨이', label: '베르겐 (BGO)', alt: 'bergen', lat: 60.2934, lng: 5.2181 },
  { code: 'TRD', city: '트론헤임', cityEn: 'Trondheim', country: '노르웨이', label: '트론헤임 (TRD)', alt: 'trondheim', lat: 63.4578, lng: 10.9240 },
  { code: 'SVG', city: '스타방에르', cityEn: 'Stavanger', country: '노르웨이', label: '스타방에르 (SVG)', alt: 'stavanger', lat: 58.8767, lng: 5.6378 },
  { code: 'HEL', city: '헬싱키', cityEn: 'Helsinki', country: '핀란드', label: '헬싱키 반타 (HEL)', alt: 'helsinki vantaa', lat: 60.3172, lng: 24.9633 },
  { code: 'TMP', city: '탐페레', cityEn: 'Tampere', country: '핀란드', label: '탐페레 (TMP)', alt: 'tampere', lat: 61.4141, lng: 23.6044 },
  { code: 'TKU', city: '투르쿠', cityEn: 'Turku', country: '핀란드', label: '투르쿠 (TKU)', alt: 'turku', lat: 60.5141, lng: 22.2628 },
  { code: 'KEF', city: '레이캬비크', cityEn: 'Reykjavik', country: '아이슬란드', label: '레이캬비크 케플라비크 (KEF)', alt: 'reykjavik keflavik iceland', lat: 63.9850, lng: -22.6056 },

  // ── 유럽 (동유럽 / 발칸 / 발트) ────────────────────
  { code: 'WAW', city: '바르샤바', cityEn: 'Warsaw', country: '폴란드', label: '바르샤바 (WAW)', alt: 'warsaw warszawa', lat: 52.1657, lng: 20.9671 },
  { code: 'WMI', city: '바르샤바', cityEn: 'Warsaw', country: '폴란드', label: '바르샤바 모들린 (WMI)', alt: 'warsaw modlin', lat: 52.4514, lng: 20.6517 },
  { code: 'KRK', city: '크라쿠프', cityEn: 'Krakow', country: '폴란드', label: '크라쿠프 (KRK)', alt: 'krakow cracow', lat: 50.0777, lng: 19.7848 },
  { code: 'GDN', city: '그단스크', cityEn: 'Gdansk', country: '폴란드', label: '그단스크 (GDN)', alt: 'gdansk danzig', lat: 54.3776, lng: 18.4662 },
  { code: 'POZ', city: '포즈난', cityEn: 'Poznan', country: '폴란드', label: '포즈난 (POZ)', alt: 'poznan', lat: 52.4210, lng: 16.8263 },
  { code: 'WRO', city: '브로츠와프', cityEn: 'Wroclaw', country: '폴란드', label: '브로츠와프 (WRO)', alt: 'wroclaw breslau', lat: 51.1027, lng: 16.8858 },
  { code: 'PRG', city: '프라하', cityEn: 'Prague', country: '체코', label: '프라하 (PRG)', alt: 'prague praha', lat: 50.1008, lng: 14.2600 },
  { code: 'BRQ', city: '브르노', cityEn: 'Brno', country: '체코', label: '브르노 (BRQ)', alt: 'brno', lat: 49.1513, lng: 16.6944 },
  { code: 'BTS', city: '브라티슬라바', cityEn: 'Bratislava', country: '슬로바키아', label: '브라티슬라바 (BTS)', alt: 'bratislava', lat: 48.1702, lng: 17.2127 },
  { code: 'KSC', city: '코시체', cityEn: 'Kosice', country: '슬로바키아', label: '코시체 (KSC)', alt: 'kosice', lat: 48.6631, lng: 21.2411 },
  { code: 'BUD', city: '부다페스트', cityEn: 'Budapest', country: '헝가리', label: '부다페스트 (BUD)', alt: 'budapest', lat: 47.4298, lng: 19.2611 },
  { code: 'OTP', city: '부쿠레슈티', cityEn: 'Bucharest', country: '루마니아', label: '부쿠레슈티 오토페니 (OTP)', alt: 'bucharest otopeni', lat: 44.5711, lng: 26.0850 },
  { code: 'CLJ', city: '클루지나포카', cityEn: 'Cluj-Napoca', country: '루마니아', label: '클루지나포카 (CLJ)', alt: 'cluj napoca', lat: 46.7852, lng: 23.6862 },
  { code: 'SOF', city: '소피아', cityEn: 'Sofia', country: '불가리아', label: '소피아 (SOF)', alt: 'sofia', lat: 42.6967, lng: 23.4114 },
  { code: 'VAR', city: '바르나', cityEn: 'Varna', country: '불가리아', label: '바르나 (VAR)', alt: 'varna', lat: 43.2321, lng: 27.8251 },
  { code: 'BEG', city: '베오그라드', cityEn: 'Belgrade', country: '세르비아', label: '베오그라드 (BEG)', alt: 'belgrade beograd', lat: 44.8184, lng: 20.3091 },
  { code: 'ZAG', city: '자그레브', cityEn: 'Zagreb', country: '크로아티아', label: '자그레브 (ZAG)', alt: 'zagreb', lat: 45.7429, lng: 16.0688 },
  { code: 'SPU', city: '스플리트', cityEn: 'Split', country: '크로아티아', label: '스플리트 (SPU)', alt: 'split', lat: 43.5389, lng: 16.2980 },
  { code: 'DBV', city: '두브로브니크', cityEn: 'Dubrovnik', country: '크로아티아', label: '두브로브니크 (DBV)', alt: 'dubrovnik', lat: 42.5614, lng: 18.2682 },
  { code: 'LJU', city: '류블랴나', cityEn: 'Ljubljana', country: '슬로베니아', label: '류블랴나 (LJU)', alt: 'ljubljana', lat: 46.2237, lng: 14.4576 },
  { code: 'SJJ', city: '사라예보', cityEn: 'Sarajevo', country: '보스니아 헤르체고비나', label: '사라예보 (SJJ)', alt: 'sarajevo', lat: 43.8246, lng: 18.3315 },
  { code: 'TIA', city: '티라나', cityEn: 'Tirana', country: '알바니아', label: '티라나 (TIA)', alt: 'tirana', lat: 41.4147, lng: 19.7206 },
  { code: 'SKP', city: '스코페', cityEn: 'Skopje', country: '북마케도니아', label: '스코페 (SKP)', alt: 'skopje', lat: 41.9616, lng: 21.6214 },
  { code: 'TGD', city: '포드고리차', cityEn: 'Podgorica', country: '몬테네그로', label: '포드고리차 (TGD)', alt: 'podgorica', lat: 42.3594, lng: 19.2519 },
  { code: 'ATH', city: '아테네', cityEn: 'Athens', country: '그리스', label: '아테네 (ATH)', alt: 'athens athinai', lat: 37.9364, lng: 23.9445 },
  { code: 'SKG', city: '테살로니키', cityEn: 'Thessaloniki', country: '그리스', label: '테살로니키 (SKG)', alt: 'thessaloniki', lat: 40.5197, lng: 22.9709 },
  { code: 'HER', city: '헤라클리온', cityEn: 'Heraklion', country: '그리스', label: '헤라클리온 크레타 (HER)', alt: 'heraklion crete', lat: 35.3397, lng: 25.1803 },
  { code: 'RHO', city: '로도스', cityEn: 'Rhodes', country: '그리스', label: '로도스 (RHO)', alt: 'rhodes', lat: 36.4054, lng: 28.0862 },
  { code: 'CFU', city: '코르푸', cityEn: 'Corfu', country: '그리스', label: '코르푸 (CFU)', alt: 'corfu kerkyra', lat: 39.6019, lng: 19.9117 },
  { code: 'JTR', city: '산토리니', cityEn: 'Santorini', country: '그리스', label: '산토리니 (JTR)', alt: 'santorini thira', lat: 36.3992, lng: 25.4793 },
  { code: 'JMK', city: '미코노스', cityEn: 'Mykonos', country: '그리스', label: '미코노스 (JMK)', alt: 'mykonos', lat: 37.4351, lng: 25.3481 },
  { code: 'KIV', city: '키시너우', cityEn: 'Chisinau', country: '몰도바', label: '키시너우 (KIV)', alt: 'chisinau kishinev', lat: 46.9277, lng: 28.9310 },
  { code: 'VNO', city: '빌뉴스', cityEn: 'Vilnius', country: '리투아니아', label: '빌뉴스 (VNO)', alt: 'vilnius', lat: 54.6341, lng: 25.2858 },
  { code: 'KUN', city: '카우나스', cityEn: 'Kaunas', country: '리투아니아', label: '카우나스 (KUN)', alt: 'kaunas', lat: 54.9639, lng: 24.0848 },
  { code: 'RIX', city: '리가', cityEn: 'Riga', country: '라트비아', label: '리가 (RIX)', alt: 'riga', lat: 56.9236, lng: 23.9711 },
  { code: 'TLL', city: '탈린', cityEn: 'Tallinn', country: '에스토니아', label: '탈린 (TLL)', alt: 'tallinn', lat: 59.4133, lng: 24.8328 },
  { code: 'KBP', city: '키이우', cityEn: 'Kyiv', country: '우크라이나', label: '키이우 보리스필 (KBP)', alt: 'kyiv kiev boryspil', lat: 50.3450, lng: 30.8947 },
  { code: 'IEV', city: '키이우', cityEn: 'Kyiv', country: '우크라이나', label: '키이우 줄랴니 (IEV)', alt: 'kyiv kiev zhuliany', lat: 50.4019, lng: 30.4519 },
  { code: 'LWO', city: '리비우', cityEn: 'Lviv', country: '우크라이나', label: '리비우 (LWO)', alt: 'lviv lvov', lat: 49.8125, lng: 23.9561 },
  { code: 'MSQ', city: '민스크', cityEn: 'Minsk', country: '벨라루스', label: '민스크 (MSQ)', alt: 'minsk', lat: 53.8825, lng: 28.0307 },
  { code: 'SVO', city: '모스크바', cityEn: 'Moscow', country: '러시아', label: '모스크바 셰레메티예보 (SVO)', alt: 'moscow sheremetyevo', lat: 55.9726, lng: 37.4146 },
  { code: 'DME', city: '모스크바', cityEn: 'Moscow', country: '러시아', label: '모스크바 도모데도보 (DME)', alt: 'moscow domodedovo', lat: 55.4088, lng: 37.9063 },
  { code: 'VKO', city: '모스크바', cityEn: 'Moscow', country: '러시아', label: '모스크바 브누코보 (VKO)', alt: 'moscow vnukovo', lat: 55.5915, lng: 37.2615 },
  { code: 'LED', city: '상트페테르부르크', cityEn: 'Saint Petersburg', country: '러시아', label: '상트페테르부르크 (LED)', alt: 'saint petersburg pulkovo', lat: 59.8003, lng: 30.2625 },

  // ── 튀르키예 / 코카서스 ─────────────────────────────
  { code: 'IST', city: '이스탄불', cityEn: 'Istanbul', country: '튀르키예', label: '이스탄불 (IST)', alt: 'istanbul', lat: 41.2753, lng: 28.7519 },
  { code: 'SAW', city: '이스탄불', cityEn: 'Istanbul', country: '튀르키예', label: '이스탄불 사비하 괵첸 (SAW)', alt: 'istanbul sabiha gokcen', lat: 40.8986, lng: 29.3092 },
  { code: 'ESB', city: '앙카라', cityEn: 'Ankara', country: '튀르키예', label: '앙카라 (ESB)', alt: 'ankara', lat: 40.1281, lng: 32.9951 },
  { code: 'ADB', city: '이즈미르', cityEn: 'Izmir', country: '튀르키예', label: '이즈미르 (ADB)', alt: 'izmir', lat: 38.2924, lng: 27.1570 },
  { code: 'AYT', city: '안탈리아', cityEn: 'Antalya', country: '튀르키예', label: '안탈리아 (AYT)', alt: 'antalya', lat: 36.8987, lng: 30.8005 },
  { code: 'TBS', city: '트빌리시', cityEn: 'Tbilisi', country: '조지아', label: '트빌리시 (TBS)', alt: 'tbilisi', lat: 41.6692, lng: 44.9547 },
  { code: 'EVN', city: '예레반', cityEn: 'Yerevan', country: '아르메니아', label: '예레반 (EVN)', alt: 'yerevan', lat: 40.1473, lng: 44.3959 },
  { code: 'GYD', city: '바쿠', cityEn: 'Baku', country: '아제르바이잔', label: '바쿠 (GYD)', alt: 'baku', lat: 40.4675, lng: 50.0467 },

  // ── 중동 ─────────────────────────────────────────────
  { code: 'DXB', city: '두바이', cityEn: 'Dubai', country: 'UAE', label: '두바이 (DXB)', alt: 'dubai', lat: 25.2528, lng: 55.3644 },
  { code: 'DWC', city: '두바이', cityEn: 'Dubai', country: 'UAE', label: '두바이 알막툼 (DWC)', alt: 'dubai al maktoum', lat: 24.8967, lng: 55.1614 },
  { code: 'AUH', city: '아부다비', cityEn: 'Abu Dhabi', country: 'UAE', label: '아부다비 (AUH)', alt: 'abu dhabi', lat: 24.4330, lng: 54.6511 },
  { code: 'SHJ', city: '샤르자', cityEn: 'Sharjah', country: 'UAE', label: '샤르자 (SHJ)', alt: 'sharjah', lat: 25.3286, lng: 55.5172 },
  { code: 'DOH', city: '도하', cityEn: 'Doha', country: '카타르', label: '도하 하마드 (DOH)', alt: 'doha hamad', lat: 25.2731, lng: 51.6081 },
  { code: 'BAH', city: '마나마', cityEn: 'Manama', country: '바레인', label: '마나마 바레인 (BAH)', alt: 'bahrain manama', lat: 26.2708, lng: 50.6336 },
  { code: 'KWI', city: '쿠웨이트시티', cityEn: 'Kuwait City', country: '쿠웨이트', label: '쿠웨이트시티 (KWI)', alt: 'kuwait city', lat: 29.2266, lng: 47.9689 },
  { code: 'MCT', city: '무스카트', cityEn: 'Muscat', country: '오만', label: '무스카트 (MCT)', alt: 'muscat oman', lat: 23.5933, lng: 58.2844 },
  { code: 'RUH', city: '리야드', cityEn: 'Riyadh', country: '사우디아라비아', label: '리야드 (RUH)', alt: 'riyadh', lat: 24.9576, lng: 46.6988 },
  { code: 'JED', city: '제다', cityEn: 'Jeddah', country: '사우디아라비아', label: '제다 (JED)', alt: 'jeddah', lat: 21.6796, lng: 39.1565 },
  { code: 'DMM', city: '담맘', cityEn: 'Dammam', country: '사우디아라비아', label: '담맘 (DMM)', alt: 'dammam', lat: 26.4712, lng: 49.7979 },
  { code: 'TLV', city: '텔아비브', cityEn: 'Tel Aviv', country: '이스라엘', label: '텔아비브 벤구리온 (TLV)', alt: 'tel aviv ben gurion', lat: 32.0114, lng: 34.8867 },
  { code: 'AMM', city: '암만', cityEn: 'Amman', country: '요르단', label: '암만 (AMM)', alt: 'amman', lat: 31.7226, lng: 35.9932 },
  { code: 'BEY', city: '베이루트', cityEn: 'Beirut', country: '레바논', label: '베이루트 (BEY)', alt: 'beirut', lat: 33.8209, lng: 35.4884 },
  { code: 'IKA', city: '테헤란', cityEn: 'Tehran', country: '이란', label: '테헤란 이맘 호메이니 (IKA)', alt: 'tehran imam khomeini', lat: 35.4161, lng: 51.1522 },

  // ── 아프리카 ─────────────────────────────────────────
  { code: 'CAI', city: '카이로', cityEn: 'Cairo', country: '이집트', label: '카이로 (CAI)', alt: 'cairo', lat: 30.1219, lng: 31.4056 },
  { code: 'HRG', city: '후르가다', cityEn: 'Hurghada', country: '이집트', label: '후르가다 (HRG)', alt: 'hurghada', lat: 27.1783, lng: 33.7994 },
  { code: 'SSH', city: '샤름엘셰이크', cityEn: 'Sharm El Sheikh', country: '이집트', label: '샤름엘셰이크 (SSH)', alt: 'sharm el sheikh', lat: 27.9773, lng: 34.3950 },
  { code: 'CMN', city: '카사블랑카', cityEn: 'Casablanca', country: '모로코', label: '카사블랑카 (CMN)', alt: 'casablanca', lat: 33.3675, lng: -7.5900 },
  { code: 'RAK', city: '마라케시', cityEn: 'Marrakech', country: '모로코', label: '마라케시 (RAK)', alt: 'marrakech marrakesh', lat: 31.6069, lng: -8.0363 },
  { code: 'TUN', city: '튀니스', cityEn: 'Tunis', country: '튀니지', label: '튀니스 (TUN)', alt: 'tunis', lat: 36.8510, lng: 10.2272 },
  { code: 'ALG', city: '알제', cityEn: 'Algiers', country: '알제리', label: '알제 (ALG)', alt: 'algiers', lat: 36.6910, lng: 3.2154 },
  { code: 'JNB', city: '요하네스버그', cityEn: 'Johannesburg', country: '남아프리카공화국', label: '요하네스버그 (JNB)', alt: 'johannesburg', lat: -26.1392, lng: 28.2460 },
  { code: 'CPT', city: '케이프타운', cityEn: 'Cape Town', country: '남아프리카공화국', label: '케이프타운 (CPT)', alt: 'cape town', lat: -33.9648, lng: 18.6017 },
  { code: 'DUR', city: '더반', cityEn: 'Durban', country: '남아프리카공화국', label: '더반 (DUR)', alt: 'durban', lat: -29.6144, lng: 31.1197 },
  { code: 'NBO', city: '나이로비', cityEn: 'Nairobi', country: '케냐', label: '나이로비 (NBO)', alt: 'nairobi', lat: -1.3192, lng: 36.9278 },
  { code: 'ADD', city: '아디스아바바', cityEn: 'Addis Ababa', country: '에티오피아', label: '아디스아바바 (ADD)', alt: 'addis ababa', lat: 8.9779, lng: 38.7993 },
  { code: 'DAR', city: '다르에스살람', cityEn: 'Dar es Salaam', country: '탄자니아', label: '다르에스살람 (DAR)', alt: 'dar es salaam', lat: -6.8781, lng: 39.2026 },
  { code: 'LOS', city: '라고스', cityEn: 'Lagos', country: '나이지리아', label: '라고스 (LOS)', alt: 'lagos', lat: 6.5774, lng: 3.3212 },
  { code: 'ABV', city: '아부자', cityEn: 'Abuja', country: '나이지리아', label: '아부자 (ABV)', alt: 'abuja', lat: 9.0068, lng: 7.2632 },
  { code: 'ACC', city: '아크라', cityEn: 'Accra', country: '가나', label: '아크라 (ACC)', alt: 'accra', lat: 5.6052, lng: -0.1668 },
  { code: 'DKR', city: '다카르', cityEn: 'Dakar', country: '세네갈', label: '다카르 (DKR)', alt: 'dakar', lat: 14.7397, lng: -17.4902 },
  { code: 'MRU', city: '모리셔스', cityEn: 'Mauritius', country: '모리셔스', label: '모리셔스 (MRU)', alt: 'mauritius port louis', lat: -20.4302, lng: 57.6836 },

  // ── 오세아니아 ───────────────────────────────────────
  { code: 'SYD', city: '시드니', cityEn: 'Sydney', country: '호주', label: '시드니 (SYD)', alt: 'sydney', lat: -33.9461, lng: 151.1770 },
  { code: 'MEL', city: '멜버른', cityEn: 'Melbourne', country: '호주', label: '멜버른 (MEL)', alt: 'melbourne', lat: -37.6733, lng: 144.8430 },
  { code: 'BNE', city: '브리즈번', cityEn: 'Brisbane', country: '호주', label: '브리즈번 (BNE)', alt: 'brisbane', lat: -27.3842, lng: 153.1170 },
  { code: 'PER', city: '퍼스', cityEn: 'Perth', country: '호주', label: '퍼스 (PER)', alt: 'perth', lat: -31.9403, lng: 115.9670 },
  { code: 'ADL', city: '애들레이드', cityEn: 'Adelaide', country: '호주', label: '애들레이드 (ADL)', alt: 'adelaide', lat: -34.9450, lng: 138.5310 },
  { code: 'CBR', city: '캔버라', cityEn: 'Canberra', country: '호주', label: '캔버라 (CBR)', alt: 'canberra', lat: -35.3069, lng: 149.1950 },
  { code: 'HBA', city: '호바트', cityEn: 'Hobart', country: '호주', label: '호바트 (HBA)', alt: 'hobart tasmania', lat: -42.8361, lng: 147.5100 },
  { code: 'OOL', city: '골드코스트', cityEn: 'Gold Coast', country: '호주', label: '골드코스트 (OOL)', alt: 'gold coast', lat: -28.1644, lng: 153.5050 },
  { code: 'CNS', city: '케언스', cityEn: 'Cairns', country: '호주', label: '케언스 (CNS)', alt: 'cairns', lat: -16.8858, lng: 145.7550 },
  { code: 'DRW', city: '다윈', cityEn: 'Darwin', country: '호주', label: '다윈 (DRW)', alt: 'darwin', lat: -12.4147, lng: 130.8770 },
  { code: 'AKL', city: '오클랜드', cityEn: 'Auckland', country: '뉴질랜드', label: '오클랜드 NZ (AKL)', alt: 'auckland new zealand', lat: -37.0081, lng: 174.7920 },
  { code: 'WLG', city: '웰링턴', cityEn: 'Wellington', country: '뉴질랜드', label: '웰링턴 (WLG)', alt: 'wellington', lat: -41.3272, lng: 174.8050 },
  { code: 'CHC', city: '크라이스트처치', cityEn: 'Christchurch', country: '뉴질랜드', label: '크라이스트처치 (CHC)', alt: 'christchurch', lat: -43.4894, lng: 172.5320 },
  { code: 'ZQN', city: '퀸스타운', cityEn: 'Queenstown', country: '뉴질랜드', label: '퀸스타운 (ZQN)', alt: 'queenstown', lat: -45.0211, lng: 168.7390 },
  { code: 'NAN', city: '난디', cityEn: 'Nadi', country: '피지', label: '난디 (NAN)', alt: 'nadi fiji', lat: -17.7554, lng: 177.4430 },
  { code: 'PPT', city: '파페에테', cityEn: 'Papeete', country: '프랑스령 폴리네시아', label: '파페에테 타히티 (PPT)', alt: 'papeete tahiti', lat: -17.5537, lng: -149.6070 },
  { code: 'NOU', city: '누메아', cityEn: 'Noumea', country: '뉴칼레도니아', label: '누메아 (NOU)', alt: 'noumea new caledonia', lat: -22.0146, lng: 166.2130 },

  // ── 남미 ─────────────────────────────────────────────
  { code: 'GRU', city: '상파울루', cityEn: 'Sao Paulo', country: '브라질', label: '상파울루 과룰류스 (GRU)', alt: 'sao paulo guarulhos', lat: -23.4356, lng: -46.4731 },
  { code: 'CGH', city: '상파울루', cityEn: 'Sao Paulo', country: '브라질', label: '상파울루 콘고냐스 (CGH)', alt: 'sao paulo congonhas', lat: -23.6261, lng: -46.6564 },
  { code: 'GIG', city: '리우데자네이루', cityEn: 'Rio de Janeiro', country: '브라질', label: '리우데자네이루 갈레앙 (GIG)', alt: 'rio de janeiro galeao', lat: -22.8100, lng: -43.2506 },
  { code: 'SDU', city: '리우데자네이루', cityEn: 'Rio de Janeiro', country: '브라질', label: '리우 산토스두몬트 (SDU)', alt: 'rio santos dumont', lat: -22.9105, lng: -43.1631 },
  { code: 'BSB', city: '브라질리아', cityEn: 'Brasilia', country: '브라질', label: '브라질리아 (BSB)', alt: 'brasilia', lat: -15.8692, lng: -47.9208 },
  { code: 'POA', city: '포르투알레그리', cityEn: 'Porto Alegre', country: '브라질', label: '포르투알레그리 (POA)', alt: 'porto alegre', lat: -29.9944, lng: -51.1714 },
  { code: 'CWB', city: '쿠리치바', cityEn: 'Curitiba', country: '브라질', label: '쿠리치바 (CWB)', alt: 'curitiba', lat: -25.5285, lng: -49.1758 },
  { code: 'SSA', city: '살바도르', cityEn: 'Salvador', country: '브라질', label: '살바도르 (SSA)', alt: 'salvador bahia', lat: -12.9086, lng: -38.3225 },
  { code: 'REC', city: '헤시피', cityEn: 'Recife', country: '브라질', label: '헤시피 (REC)', alt: 'recife', lat: -8.1265, lng: -34.9236 },
  { code: 'FOR', city: '포르탈레자', cityEn: 'Fortaleza', country: '브라질', label: '포르탈레자 (FOR)', alt: 'fortaleza', lat: -3.7763, lng: -38.5326 },
  { code: 'MAO', city: '마나우스', cityEn: 'Manaus', country: '브라질', label: '마나우스 (MAO)', alt: 'manaus', lat: -3.0386, lng: -60.0497 },
  { code: 'BEL', city: '벨렘', cityEn: 'Belem', country: '브라질', label: '벨렘 (BEL)', alt: 'belem', lat: -1.3793, lng: -48.4763 },
  { code: 'EZE', city: '부에노스아이레스', cityEn: 'Buenos Aires', country: '아르헨티나', label: '부에노스아이레스 에세이사 (EZE)', alt: 'buenos aires ezeiza', lat: -34.8222, lng: -58.5358 },
  { code: 'AEP', city: '부에노스아이레스', cityEn: 'Buenos Aires', country: '아르헨티나', label: '부에노스아이레스 호르헤뉴베리 (AEP)', alt: 'buenos aires aeroparque', lat: -34.5592, lng: -58.4156 },
  { code: 'COR', city: '코르도바', cityEn: 'Cordoba', country: '아르헨티나', label: '코르도바 (COR)', alt: 'cordoba argentina', lat: -31.3236, lng: -64.2080 },
  { code: 'MVD', city: '몬테비데오', cityEn: 'Montevideo', country: '우루과이', label: '몬테비데오 (MVD)', alt: 'montevideo', lat: -34.8384, lng: -56.0308 },
  { code: 'SCL', city: '산티아고', cityEn: 'Santiago', country: '칠레', label: '산티아고 (SCL)', alt: 'santiago chile', lat: -33.3930, lng: -70.7858 },
  { code: 'LIM', city: '리마', cityEn: 'Lima', country: '페루', label: '리마 호르헤차베스 (LIM)', alt: 'lima jorge chavez', lat: -12.0219, lng: -77.1143 },
  { code: 'BOG', city: '보고타', cityEn: 'Bogota', country: '콜롬비아', label: '보고타 (BOG)', alt: 'bogota', lat: 4.7016, lng: -74.1469 },
  { code: 'MDE', city: '메데인', cityEn: 'Medellin', country: '콜롬비아', label: '메데인 호세마리아 (MDE)', alt: 'medellin', lat: 6.1645, lng: -75.4231 },
  { code: 'CTG', city: '카르타헤나', cityEn: 'Cartagena', country: '콜롬비아', label: '카르타헤나 (CTG)', alt: 'cartagena colombia', lat: 10.4424, lng: -75.5130 },
  { code: 'CLO', city: '칼리', cityEn: 'Cali', country: '콜롬비아', label: '칼리 (CLO)', alt: 'cali', lat: 3.5432, lng: -76.3816 },
  { code: 'UIO', city: '키토', cityEn: 'Quito', country: '에콰도르', label: '키토 (UIO)', alt: 'quito', lat: -0.1292, lng: -78.3575 },
  { code: 'GYE', city: '과야킬', cityEn: 'Guayaquil', country: '에콰도르', label: '과야킬 (GYE)', alt: 'guayaquil', lat: -2.1574, lng: -79.8836 },
  { code: 'LPB', city: '라파스', cityEn: 'La Paz', country: '볼리비아', label: '라파스 (LPB)', alt: 'la paz bolivia', lat: -16.5133, lng: -68.1923 },
  { code: 'VVI', city: '산타크루스', cityEn: 'Santa Cruz', country: '볼리비아', label: '산타크루스 (VVI)', alt: 'santa cruz bolivia', lat: -17.6448, lng: -63.1354 },
  { code: 'ASU', city: '아순시온', cityEn: 'Asuncion', country: '파라과이', label: '아순시온 (ASU)', alt: 'asuncion', lat: -25.2400, lng: -57.5200 },
  { code: 'CCS', city: '카라카스', cityEn: 'Caracas', country: '베네수엘라', label: '카라카스 (CCS)', alt: 'caracas', lat: 10.6012, lng: -66.9912 },
  { code: 'PTY', city: '파나마시티', cityEn: 'Panama City', country: '파나마', label: '파나마시티 (PTY)', alt: 'panama city', lat: 9.0714, lng: -79.3835 },
  { code: 'SJO', city: '산호세', cityEn: 'San Jose', country: '코스타리카', label: '산호세 코스타리카 (SJO)', alt: 'san jose costa rica', lat: 9.9939, lng: -84.2088 },
  { code: 'GUA', city: '과테말라시티', cityEn: 'Guatemala City', country: '과테말라', label: '과테말라시티 (GUA)', alt: 'guatemala city', lat: 14.5833, lng: -90.5275 },
  { code: 'SAL', city: '산살바도르', cityEn: 'San Salvador', country: '엘살바도르', label: '산살바도르 (SAL)', alt: 'san salvador', lat: 13.4409, lng: -89.0557 },
  { code: 'TGU', city: '테구시갈파', cityEn: 'Tegucigalpa', country: '온두라스', label: '테구시갈파 (TGU)', alt: 'tegucigalpa', lat: 14.0609, lng: -87.2172 },
  { code: 'HAV', city: '아바나', cityEn: 'Havana', country: '쿠바', label: '아바나 (HAV)', alt: 'havana habana', lat: 22.9892, lng: -82.4091 },
  { code: 'SDQ', city: '산토도밍고', cityEn: 'Santo Domingo', country: '도미니카공화국', label: '산토도밍고 (SDQ)', alt: 'santo domingo', lat: 18.4297, lng: -69.6689 },
  { code: 'PUJ', city: '푼타카나', cityEn: 'Punta Cana', country: '도미니카공화국', label: '푼타카나 (PUJ)', alt: 'punta cana', lat: 18.5674, lng: -68.3634 },
  { code: 'NAS', city: '나소', cityEn: 'Nassau', country: '바하마', label: '나소 (NAS)', alt: 'nassau bahamas', lat: 25.0390, lng: -77.4662 },
  { code: 'KIN', city: '킹스턴', cityEn: 'Kingston', country: '자메이카', label: '킹스턴 자메이카 (KIN)', alt: 'kingston jamaica', lat: 17.9357, lng: -76.7875 },
  { code: 'MBJ', city: '몬테고베이', cityEn: 'Montego Bay', country: '자메이카', label: '몬테고베이 (MBJ)', alt: 'montego bay', lat: 18.5037, lng: -77.9134 },
  { code: 'AUA', city: '아루바', cityEn: 'Aruba', country: '아루바', label: '아루바 오라녜스타트 (AUA)', alt: 'aruba oranjestad', lat: 12.5014, lng: -70.0152 },
  { code: 'CUR', city: '퀴라소', cityEn: 'Curacao', country: '퀴라소', label: '퀴라소 (CUR)', alt: 'curacao', lat: 12.1889, lng: -68.9598 }
];
